<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>

    <RootNamespace>Fluxion.Desktop</RootNamespace>
    <AssemblyName>Fluxion.Desktop</AssemblyName>

    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenTK.GLWpfControl"
                      Version="4.3.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fluxion.csproj" />
  </ItemGroup>

</Project>